name: embeddings

channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
  
dependencies:
  - python=3.9
  - pytorch::pytorch-cuda=11.7
  - pytorch::pytorch>=2.0
  - pytorch::torchvision>=0.14.1
  - pytorch::torchaudio>=0.13.1
  - numpy>=1.23.5
  - pandas>=1.5.2
  - scikit-learn>=1.2.0
  - jupyter>=1.0.0
  - jupyterlab>=3.5.3
  - seaborn>=0.12.2
  - matplotlib>=3.6.2
  - pytest==7.1.2
  - pytest-cov==3.0.0
  - codecov==2.1.11
  - mypy==0.981
  - pip>=21.0.1
  - tqdm>=4.64
  - pyarrow>=8.0.0
  - pytables>=3.7.0
  - black==22.6.0
  - isort==5.9.3
  - pyspark>=3.2.1
  - fdasrsf>=2.2.8
  - lightgbm>=3.2.1
  - ignite>=0.4.4
  - gin-config>=0.5.0
  - tensorboard>=2.11.0
  - accelerate>=0.18.0
  - pip:
    - deepspeed>=0.8.3
    - h5py>=3.1.0
    - pathos>=0.2.9
    - scikit-fda>=0.8.1
    - torch_tb_profiler
    - routing-transformer>=1.5.1
